# Generated by Django 4.2.12 on 2024-05-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
